# Generated by Django 3.2 on 2022-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symmap3_herb_herb_cosine_jiaoji',
            name='herb',
        ),
        migrations.AddField(
            model_name='symmap3_herb_herb_cosine_jiaoji',
            name='herb1',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symmap3_herb_herb_cosine_jiaoji',
            name='herb2',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symmap3_herb_mm_symp_jiaoji',
            name='Gene',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='symmap3_herb_mm_symp_jiaoji',
            name='Herb',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='symmap3_herb_target_jiaoji',
            name='Gene',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='symmap3_herb_target_jiaoji',
            name='Herb',
            field=models.CharField(max_length=128),
        ),
    ]
